#!/usr/bin/env ruby
# frozen_string_literal: true

STDOUT.sync = true

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)

require 'rscheme'

repl = Rscheme::Repl.new

loop do
  print '> '
  s = readline
  result = repl.eval s.chomp
  puts result.to_s
end

